### ISSUE TITLE
Unzuverlässige Schaltung

### ISSUE THREAD

**Issue by l4ci** [ChristopherNeuwirth/homebridge-rc433-etekcity#1]
Moin und hallo aus Hamburg!

ich nutze dein Plugin und hab die Frequenzen für alle Steckdosen herausgefiltert und entsprechend eingestellt.

Es können also alle bedient werden - nur funktioniert das ziemlich unzuverlässig.

Von 3 Steckdosen im selben Raum, kann nur eine an UND aus geschaltet werden. Die restlichen 2 kann ich nur ausschalten (und sehr selten mal an). Habe schon überprüft ob sich evtl die Frequenz der Dosen ändert, der Sniffer zeigt mir aber diese unverändert an (und manchmal geht es ja auch an).

Frage mich jetzt woran das liegen kann - habe an meinem RPI Sender noch keine extra Antenne - die kommt erst nächste Woche. Wobei eine zu schwache Sendeleistung eigentlich nicht sein kann, da die Dose die funktioniert am weitesten weg ist - und die anderen auch nicht funktionieren wenn ich den Pi direkt davor stelle.

Hast du noch eine Idee woran das liegen könnte?

**Comment by ChristopherNeuwirth** [comment]
Hi,

(TL;DR -> Scrolle ganz runter)

ich kenne dieses Problem nur zu gut. Bei mir war es auch sehr paradox, da ich Steckdosen die sehr weit entfernt waren perfekt ansteuern konnte und eine, die quasi direkt daneben lag war äußerst unzuverlässig.

Das Problem kann mehrere Ursachen haben. Sehr unwahrscheinlich aber trotzdem möglich: Spiel mal ein bisschen mit der Pulslänge. Bei den Fernbedienungen von mir variierte die Pulslänge immer zwischen 180 und 182. Bei mir im Plugin sind aktuell noch 179 als fixer Wert eingestellt, da ich damit das beste Ergebnis erzielen konnte. 

Ansonsten wenn das nichts hilft wird es wohl das selbe sein wie bei mir, die Reichweite der Antenne. Die 433mhz Technologie ist leider sehr anfällig für elektromagnetische Störungen. Wenn du den Sender so angeschlossen hast wie in der Readme dargestellt versorgt der Raspberry den 433mhz Sender mit 5v. Die Antenne erreicht ihre maximale Sendeleistung allerdings erst bei 12v. Du kannst den Raspberry prinzipiell so verkabeln dass er den Strom über die GPIO Pins zieht und so dann entsprechend 12v an den 433mhz Sender legen, oder du machst es so wie ich: 

TL;DR: 
Löte ein Kabel als Antenne (bei mir ca. 10-15cm) an den Sender und lass' es aus dem Raspberry Gehäuse hinten raus hängen. Seitdem habe ich keine Probleme mehr. 

Falls das nicht hilft melde dich gerne nochmal. 
Schönen Sonntag noch,
Grüße aus Ludwigsburg

**Comment by l4ci** [comment]
Danke, werde berichten ob die Antenne Besserung bringt.

Pulslänge habe ich schon etwas rumprobiert, 182/181 scheint bei mir besser zu klappen.

Baust du die Pulslänge später noch variabel für jeden Schalter ein? Ist derzeit ja schon angedacht wie ich sehe.

**Comment by ChristopherNeuwirth** [comment]
ja mach das auf jeden Fall. 

Das ist richtig, sobald ich mal wieder ein wenig Zeit habe, möchte ich das ganze noch etwas ausbauen und performanter gestalten. 

Es wird auch ein kleines CLI-Tool dazu kommen, dass virtuelle Gruppen ausgibt, also Codes die nicht von der Fernbedienung abhängig sind.
