### ISSUE TITLE
The Scenes in the Home App are not Working

### ISSUE THREAD

**Issue by skip14** [ChristopherNeuwirth/homebridge-rc433-etekcity#2]
Hey, if i tried to activate a scene in the "Home" app. Nothing is happened with my lights but the Terminal shows that homebridge sended the code. 

Have you any idea to fix it?

**Comment by ChristopherNeuwirth** [comment]
Hi there, 
thank you for getting in touch. Well that could have different causes. Can you provide me some more information about your problem like:

1. Is just the "scene" not working or isn't it even possible to control your lights by the switch in homekit itself? 
2. Is the device you try to control in range, so does it work if you put your raspberry and your switch right next to it? 
3. If your log files show the code, does it match your codes and have you assigned them to the switches?
4. Have you wired the pi correctly, so for instance is it possible to control the switch by using wiring-pi?

Greetings from Germany

**Comment by skip14** [comment]
Hallo Christopher, 

dann kann ich dir ja auch auf Deutsch schreiben:

- es klappen nur die Szenen nicht und auch nur dann wenn mehr als ein Gerät in eine Szene ist. 
(Eine Szene mit nur einem Gerät geht)

-das normale schalten jeder einzelnen Lampe klappt über die App und der Pi steht eigentlich an der optimalen Position

- die übermittelten Codes passen auch die er mir im Log anzeigt 

- somit sollte auch die Verkabelung passen

Meine Vermutung ist das die Signale zu schnell hintereinander / oder gleichzeitig gesendet werden so das der Sender nicht so schnell unterschiedliche Signale schicken kann.

Hast du vielleicht eine Idee?

Viele Grüße aus Frankfurt 

Dominik

Von meinem iPhone gesendet

**Comment by ChristopherNeuwirth** [comment]
Hello,

ja das habe ich mir gedacht. Also:

Es gibt aktuell kein Chaining bzw. Queuing System. D.h. wenn du mehrere Geräte in eine Szene einbindest schickt HomeKit mehr oder weniger gleichzeitig die Befehle an alle Geräte in der Szene. Da Die Homebridge Komponente ja eigentlich ein "virtuelles Gerät" ist, dass dann in dem Fall mehrere Signale abbekommt wird eben das erste oder manchmal auch keines angenommen, wenn du versucht mehrere Steckdosen gleichzeitig zu steuern (Irgendwo zwischen dem Trigger und den GPIO Outlets läuft da dann was schief, deshalb auch der Log, dass der Code gesendet wurde).

Was du machen kannst: 

Der Code des On und Off-Signals unterscheidet sich bei mir im Dezimalsystem immer genau um 9. Ich habe mir alle meine Codes in das Binärsystem umgerechnet. Dann erkennst du bei allen Codes einen Codestream der für alle gleich ist. Die Stellen danach sind alle individuell. Wenn du in dem Teil an paar Bits veränderst und das wieder zurück ins Dezimalsystem rechnest hast du einen neuen Code. Den korrespondierenden Off (oder On je nachdem was du dir nimmst) erhält du durch die Differenz (bei mir 9). Achte aber darauf dass der neue Code in einem gewissen Abstand zu allen anderen Codes steht. 

Diese virtuelle neue Gruppe die du dir eben ausgerechnet hast kannst du nun als neues Gerät in Homebridge einbinden und allen Steckdosen zuweisen die du mit deiner Szene steuern möchtest (wie das geht und wie du die Schalter komplett resetest steht in der Anleitung). Danach weist den virtuellen HomeKit Switch (der stellvertretend für alle Geräte steht die du steuern möchtest) der Szene zu und danach sollte es gehen.

Einziges Manko an der Variante: Wenn du die Geräte in der Szene aktivierst updatet sich nicht der Status der anderen Schalter. Dies könnte man aber auch softwareseitig lösen.

Chaining-System steht aber auf der ToDo Liste.

<img width="320" alt="bildschirmfoto 2017-02-21 um 12 03 55" src="https://cloud.githubusercontent.com/assets/11662358/23162611/2fa8c5f2-f82f-11e6-86ea-4337b6ef9baf.png">
Hier ein Beispiel einer neuen Gruppe, falls das nicht mit einem deiner Standard-Codes in Konflikt steht kannst du den ja mal ausprobieren.

![img_6915](https://cloud.githubusercontent.com/assets/11662358/23162614/3450a994-f82f-11e6-99f9-3a0160cfd098.PNG)

Ich hoffe das hilft dir erstmal weiter. 
Gib' mir auf jeden Fall Rückmeldung ob das dein Problem gelöst hat.

Grüße
Christopher

**Comment by skip14** [comment]
Hallo,

also ich habe es jetzt noch anders gemacht und zwar löse ich jetzt das code send wieder über FHEM aus wie ich es anfangs auch gemacht habe mit dem unterschied das ich jetzt vor jedem codesend das ich auslöse ein sleep packe, welches ich von Stecker zu Stecker um 0.6 s variiere… und siehe da es klappt! 

Danke schon mal für deine Hilfe! 

Viele Grüße

Dominik

**Comment by ChristopherNeuwirth** [comment]
Hi,

danke dir für deine Rückmeldung, freut mich wenn du eine passende Lösung für dich gefunden hast.

**Comment by mxmerz** [comment]
Hallo,

ich habe leider das selbe Problem.
Wie sieht es denn mit dem Chaining-System aus? Würde dir auch gerne einen Pull Request vorbereiten, weiß nur nicht was du dir vorstellst bzw. wie das mit der API von Homebridge funktionieren soll?

Grüße
Max

**Comment by ChristopherNeuwirth** [comment]
Hi,

du kannst gerne einen PR stellen, feel free :-) 
Ich habe jetzt schon länger nichts mehr an dem PlugIn gemacht, da der oben beschriebene Workaround meine täglichen Anforderungen super abfängt. Wenn ich das noch richtig im Kopf habe sollte das relativ entkoppelt von Homebridge laufen. Mein Ansatz wäre zumindest gewesen das direkt in dem Plugin zu verankern und Homebridge so gut es geht rauszuhalten.

Also wenn du Lust hast kannst du gerne daran rumbasteln, ich bin offen für alle Vorschläge. 

Grüße
Christopher
