### ISSUE TITLE
‘pulse’ Config Parameter Not Used

### ISSUE THREAD

**Issue by mxmerz** [ChristopherNeuwirth/homebridge-rc433-etekcity#4]
The sample config contains a ‘pulse‘ parameter, which is read from the config file in the code but never used. Instead, the constant 178 is supplied to the rpi433 emitter.

**Comment by JustAnotherPU** [comment]
same issue here seems the dev doesn't care too bad that could have been a great plugin !

**Comment by JustAnotherPU** [comment]
@mxmerz did you figure out something ?

**Comment by ChristopherNeuwirth** [comment]
instead of complaining you just can contribute like @mxmerz did. With the force of an open source community it can be an awesome plugin mate 💪. So create a pull request. There is no sense in a 3rd clone of this repo which does not get maintained. 

For questions or suggestions I am always open. 🙌
