### ISSUE TITLE
how to chose pin?

### ISSUE THREAD

**Issue by toshibochan** [ChristopherNeuwirth/homebridge-rc433-etekcity#5]
how to setup GPIO pin on the config?

**Comment by ChristopherNeuwirth** [comment]
I did not yet made this configurable.
You find it in `index.js` Line 2:

`const rfEmitter = rpi433.emitter({pin: 0, pulseLength: 179});`

The "pin" option should do the trick. 
You can open a pull request to make this configurable by the config file.
