### ISSUE TITLE
dosn't compile without lcrypt 

### ISSUE THREAD

**Issue by ufehembach** [ChristopherNeuwirth/homebridge-rc433-etekcity#6]
hi, 
the sendkey needs to be compiled with lcrypt and others on my raspi / ubuntu

Linux MYhomebridge 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux
Ubuntu 16.04.5 LTS

I need to add "-lwiringPi -pthread -lwiringPiDev -lcrypt -lm -lrt", then it compiles, but I can not tweak the npm module before compiling.

uwe

**Comment by ChristopherNeuwirth** [comment]
Hi, 
sorry I somehow have overseen your issue, really sorry for that. If you still have issues please let me know, I'll try to help you out.
Greetings
Christopher
